gal/urls.py
from django.urls import path
from .views import GalListView, GalView, GalSearchDirListView

app_name = 'gal'

urlpatterns = [
    path('list/<str:dirname>', GalView.as_view(), name='listdir'),
    path('searchdir/', GalSearchDirListView.as_view(), name='searchdir'),
    path('list/', GalListView.as_view(), name='list'),
]

pmap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from gal.views import GalListView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('file/', include("file.urls")),
    path('map/', include('map.urls')),
    path('gal/', include('gal.urls')),
    path('', GalListView.as_view(), name='home'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #讓網址media對應到資料夾media

gal/models.py
from django.db import models

# Create your models here.

gal/views.py
import os
from django.shortcuts import render
from map.models import Img
from django.views.generic import TemplateView, ListView
from pmap import settings
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from map.models import Img

class GalView(TemplateView): #將指定資料夾下不是tH開頭的圖片製作成相簿
    template_name = 'img.html'
    imgpath = str(settings.BASE_DIR)+ "/media/img/"
    queryset = {}

    def get_context_data(self, **kwargs):
        dir = kwargs['dirname']
        imgs = Img.objects.filter(dirname=dir).exclude(filename__startswith='tH') #取出指定資料夾，排除tH開頭的縮圖
        context = super().get_context_data(**kwargs)
        context["imgs"] = imgs
        return context
    
class GalListView(ListView): #列出media/img下的所有子資料夾，每分頁10個資料夾
    template_name = 'gallist.html'
    queryset = {}
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        imgpath = str(settings.BASE_DIR)+ "/media/img/"
        dirs = [d for d in os.listdir(imgpath) if os.path.isdir(os.path.join(str(settings.BASE_DIR)+ "/media/img/", d))] #找出子資料夾
        context["dirs"] = dirs
        limit = 10  #每個分頁10個資料夾
        paginator = Paginator(dirs, limit)  #設定分頁的資料夾數量
        page = self.request.GET.get('page')  #取出網址的page的值(?page=xx)
        try:
            dirp = paginator.page(page)  #指定第幾個page
        except PageNotAnInteger:  #page不是整數
            dirp = paginator.page(1)  #指定第一個分頁
        except EmptyPage:  #不存在的分頁
            dirp = paginator.page(1)  #指定第一個分頁
        context["dirp"] = dirp
        return context

class GalSearchDirListView(ListView):  #使用字串搜尋資料夾media\img下的子資料夾名稱
    template_name = 'galsearchdirlist.html'
    queryset = {}
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.method == 'GET':
            query = self.request.GET['query'] #取出網址的page的字串(?query=xxx)
            imgs = Img.objects.filter(dirname__contains=query) #取出所有子資料夾名稱是否包含字串query
            dirs = []
            for item in imgs: #所有資料夾名稱只取一次
                if item.dirname not in dirs: dirs.append(item.dirname)
            context["dirs"] = dirs
        return context

gal/templates/gallist.html
{% extends "base.html" %}

{% block content %} 
<form action="{% url 'gal:searchdir' %}" method="get">
  <label for="dir">輸入要搜尋的字串 </label>
  <input
    type="text"
    name="query"
    value="" />
  <input type="submit" value="送出" />
</form>

  <h3>相簿</h3>
{% if dirp %}
  {% for dir in dirp.object_list %}
  <li  class="list-group-item list-group-item-success h4">
    <a href="{% url 'gal:listdir' dir %}">{{ dir }}</a>
  </li>
  {% endfor %}
  <ul class="pagination">
  {% for page_number in dirp.paginator.page_range %}
    {% if page_number == dirp.number %}
    <li class="page-item active"><a class="page-link">{{ page_number }}</a></li>
    {% else %}
    <li class="page-item"><a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a></li>
    {% endif %}
  {% endfor %}
  </ul>
{% else %}
<p>沒有圖片資料夾</p>
{% endif %}
{% endblock %}

gal/templates/galsearchdirlist.html
{% extends "base.html" %}

{% block content %}
  <h3>相簿名稱的搜尋結果</h3>
{% if dirs %}
  {% for dir in dirs %}
  <li  class="list-group-item list-group-item-success h4">
    <a href="{% url 'gal:listdir' dir %}">{{ dir }}</a>
  </li>
  {% endfor %}
{% else %}
<p>沒有圖片資料夾</p>
{% endif %}
{% endblock %}

gal/templates/img.html
{% extends "base.html" %}

{% block content %}
<div id="nanogallery2"></div>
<script>
$("#nanogallery2").nanogallery2({
thumbnailWidth: 200, // 縮圖寬度
thumbnailHeight: 200, // 縮圖高度
galleryDisplayMode: "moreButton",
galleryDisplayMoreStep: 4, // 最多顯示幾行
<!-- IMAGES -->
{% if imgs %}
    items: [
    {% for img in imgs %}
        {src: "{{MEDIA_URL}}img/{{img.dirname}}/{{img.filename}}",
        srct: "{{MEDIA_URL}}img/{{img.dirname}}/{{img.filename}}",
        title: '{{img.dirname}}'},
    {% endfor %} ]
{% else %}
    <p>沒有圖片</p>
{% endif %}
});
</script>
{% endblock %}