file/urls.py
from . import views
from django.urls import path

app_name = "file"

urlpatterns = [
    path("", views.uploadFile, name = 'upload'),
    path('del/<int:pk>', views.deleteFile, name = 'delete'),
    path('download/<int:pk>', views.downloadFile, name = 'download'),
    path('unzip/<int:pk>', views.unzipFile, name = 'unzip'),
    path('thumb/<int:pk>', views.makeThumbnail, name = 'thumb'),
]

gal/urls.py
from django.urls import path
from .views import GalListView, GalView, GalSearchDirListView

app_name = 'gal'

urlpatterns = [
    path('list/<str:dirname>', GalView.as_view(), name='listdir'),
    path('searchdir/', GalSearchDirListView.as_view(), name='searchdir'),
    path('list/', GalListView.as_view(), name='list'),
]

map/urls.py
from django.urls import path
from .views import MapView,  MapListView

app_name = 'map'

urlpatterns = [
    path('list/<str:dirname>', MapView.as_view(), name='listdir'),
    path('list/', MapListView.as_view(), name='list'),
]

pmap/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from gal.views import GalListView

urlpatterns = [
    path("admin/", admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('file/', include("file.urls")),
    path('map/', include('map.urls')),
    path('gal/', include('gal.urls')),
    path('', GalListView.as_view(), name='home'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #讓網址media對應到資料夾media

map/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class Img(models.Model):
    lat = models.FloatField(verbose_name=_('latitude'), help_text=_('latitude'))  #緯度
    lng = models.FloatField(verbose_name=_('longitude'), help_text=_('longitude'))  #經度
    imgtime = models.DateTimeField(default=timezone.now)
    filename = models.CharField(max_length=100, verbose_name=_('filename'), help_text=_('filename'))
    dirname = models.CharField(max_length=100, verbose_name=_('dirname'), help_text=_('dirname'))
    path = models.CharField(max_length=200, verbose_name=_('path'), help_text=_('path'), default='')
    def __str__(self):
        return self.filename

map/views.py
from django.views.generic import TemplateView, ListView
import folium
import base64
import os
from map.models import Img
from pmap import settings
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

class MapView(TemplateView): #列出指定資料夾下所有圖片到地圖上
    template_name = 'map.html'    

    def get_gps(self, dirname):  #傳回指定資料夾內的第一個圖片GPS
        path = str(settings.BASE_DIR)+ "/media/img/"+ dirname #子資料夾路徑
        files = [f for f in os.listdir(path) if os.path.isfile(os.path.join(path,f)) and f[0:2]=='tH'] #找出子資料夾下的tH開頭的縮圖圖檔
        first = Img.objects.filter(filename=files[0])
        return {'lat':first[0].lat, 'lng':first[0].lng} #回傳第一個圖檔的GPS
    
    def get_context_data(self, **kwargs):
        dirname = kwargs['dirname']
        figure = folium.Figure()
        img_gps = self.get_gps(dirname) #取出第一個圖檔的GPS座標來建立地圖的起始位置
        #建立地圖
        map = folium.Map( 
            location = [img_gps['lat'], img_gps['lng']], #地圖開始的所在GPS
            zoom_start = 16,  #地圖縮放程度
            tiles = 'OpenStreetMap')  #使用的地圖系統
        map.add_to(figure)
        
        for imgexif in Img.objects.filter(dirname=dirname, filename__startswith="tH"): #只取資料庫內指定dirname的資料夾內，開頭是tH的圖片
            #使用popup建立彈出的圖片
            encoded = base64.b64encode(open(imgexif.path +'/'+imgexif.filename, 'rb').read())
            html = '<img src="data:image/jpeg;base64,{}">'.format
            iframe = folium.IFrame(html(encoded.decode('UTF-8')), width=170, height=170)
            x = folium.Popup(iframe, max_width=180)

            #將上方popup新增到此marker
            folium.Marker(
                location = [imgexif.lat, imgexif.lng],
                popup = x,
                tooltip = imgexif.dirname,
                icon = folium.Icon(icon='fa-mountain', prefix='fa')
            ).add_to(map)
        
        #與樣板map.html結合
        figure.render()
        return {"map": figure}


class MapListView(ListView):  #列出資料夾media\img下所有子資料夾，每分頁10個資料夾
    template_name = 'maplist.html'
    queryset = {}
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        imgpath = str(settings.BASE_DIR)+ "/media/img/"
        dirs = [d for d in os.listdir(imgpath) if os.path.isdir(os.path.join(str(settings.BASE_DIR)+ "/media/img/", d))] #找出子資料夾
        context["dirs"] = dirs
        limit = 10  #每個分頁10個資料夾
        paginator = Paginator(dirs, limit)  #設定分頁的資料夾數量
        page = self.request.GET.get('page')  #取出網址的變數page的值(?page=xx)
        try:
            dirp = paginator.page(page)  #指定第幾個page
        except PageNotAnInteger:  #page不是整數
            dirp = paginator.page(1)  #指定第一個分頁
        except EmptyPage:  #不存在的分頁
            dirp = paginator.page(1)  #指定第一個分頁
        context["dirp"] = dirp
        return context

templates/base.html
{% load static %}
<!doctype html>
<html lang="zh-Hant">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1">

    <!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <!-- nanogallery2 CSS -->
<!-- jQuery -->
<script  type="text/javascript"  src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<!-- nanogallery2 -->
<script src='//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js'></script>
<link href="https://unpkg.com/nanogallery2/dist/css/nanogallery2.min.css" rel="stylesheet" type="text/css"></link>
<script type="text/javascript" src="https://unpkg.com/nanogallery2/dist/jquery.nanogallery2.min.js"></script>

    <title>相簿地圖</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <a class="navbar-brand" href="#" target="_blank">
          <img src="{% static 'navbar/tree.jpg' %}" width="50" height="50" alt="">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'gal:list' %}">相簿</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'map:list' %}">相簿地圖</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'file:upload' %}">上傳相簿</a>
            </li>
          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              登入帳號：{{request.user}}
            </li>
            <li class="nav-item">
              <a class="nav-link" href= "{% url 'logout' %}">登出</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href= "{% url 'login' %}">登入</a>
            </li>
            {% endif %}
             
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
        <br />
        {% block content %}
        {% endblock  %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>>
  </body>
</html>

templates/map.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>台北大縱走</title>
    {{map.header.render|safe}}
  </head>
  <body>
    {{map.html.render|safe}}
    <script>
      {{map.script.render|safe}}
    </script>   
  </body>
</html>